server {
    listen 80;
    server_name anontool.darasoft.kz;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name anontool.darasoft.kz;

    ssl_certificate     /opt/AnonTool/certbot/conf/live/anontool.darasoft.kz/fullchain.pem;
    ssl_certificate_key /opt/AnonTool/certbot/conf/live/anontool.darasoft.kz/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    client_max_body_size 25m;

    location / {
        proxy_pass http://127.0.0.1:8501;
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }
}
